apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: fzo-data
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  serviceName: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: database-volume-claim

      containers:
      - name: database
        # image
        image: bitnami/postgresql:14.8.0-debian-11-r66
        imagePullPolicy: Always

        # ports
        ports:
        - name: postgres
          containerPort: 5432

        # config
        env:
          - name: POSTGRESQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: database
                key: username
          - name: POSTGRESQL_DATABASE
            value: "people"
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: password
          - name: POSTGRESQL_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: root_password

        # probes
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -U postgres -d people
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 5

        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - exec pg_isready -U postgres -d people
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2
        
        # resource limits
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
