apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fzo-frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: http